### ISSUE TITLE
Update material icons and roboto font to the latest version

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar-extras#11]
Both have changed quite a bit.

Material icons' css include the property font-size which is not included in the current version css. It should be removed to preserve back compat.

**Comment by rstoenescu** [comment]
They are latest version. Can you detail what exactly is bothering you, please?

**Comment by wc-matteo** [comment]
Look for the font x-height and the smiley icons differences.
The version included with quasar has the smiley with the X for the eyes, the other one is from google CDN.

![output_9tt4ad](https://user-images.githubusercontent.com/10562635/36202668-09151a38-1185-11e8-8d63-77f2f2ef2a95.gif)

**Comment by rstoenescu** [comment]
Now I see.

It means Google has not yet updated their icon repository (https://github.com/google/material-design-icons/). Quasar-extras uses version 3.0.1 for Material Icons, which as it seems it's the latest: https://github.com/google/material-design-icons/releases
Maybe it's worth opening up a ticket for them to figure it out? Mention CDN font icon differs from their v3.0.1 from the npm package.

As for the Roboto font, I'll investigate and fix tomorrow. Will see what they changed in their CDN.
Thanks for reporting!

**Comment by rstoenescu** [comment]
After much time lost investigating, it seems that the CDN uses some other versioning system for both Material icons and Roboto font. Replaced quasar-extras fonts with CDN ones.
Will be available in CLI v0.16.x in a few days.
