### ISSUE TITLE
Fontawesome paypal icons broken

### ISSUE THREAD

**Issue by salsa2k** [quasarframework/quasar-extras#12]
Fontawesome paypal icons not loading:
- fa-paypal
- fa-cc-paypal

`<q-btn icon="fa-cc-paypal">Paypal</q-btn>`

Fontawesome version: 5.0.1

**Comment by rstoenescu** [comment]
It's "fa fab fa-cc-paypal" for v0.14 and "fab fa-cc-paypal" for v0.15.
Notice that for v0.15 it's exactly the string in their docs: "fab fa-cc-paypal" -- fab/fas/fal/etc then fa-<icon_name>

**Comment by rstoenescu** [comment]
Correction for v0.14: "fa-cc-paypal fab"
