### ISSUE TITLE
Update font-awesome to the latest version.

### ISSUE THREAD

**Issue by salsa2k** [quasarframework/quasar-extras#13]
Hi,

Many icons has been added in the latests versions of font-awesome since 5.0.1 (current).

https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md

Thanks

**Comment by rstoenescu** [comment]
Hi,

5.0.1 is the current Fontawesome version embedded. Update to latest CLI which has it (if you're using v0.15), or update your quasar-extras dependency if you're on pre-v0.15.

**Comment by rstoenescu** [comment]
I read wrong, as if you wanted 5.0.1. Sorry.

**Comment by salsa2k** [comment]
No problem, I have created a pull request with the latest change (5.0.9)

**Comment by rstoenescu** [comment]
Seems like they released 5.0.10 too. Updated quasar-extras for Fontawesome and MDI.
Will be available along with the CLI with Webpack 4.

Sorry it takes so long.
