### ISSUE TITLE
mdi missing some icons

### ISSUE THREAD

**Issue by ftKnox** [quasarframework/quasar-extras#16]
looks like there is a newer version available, notably missing "light-switch" icon

**Comment by rstoenescu** [comment]
Hi,

I updated MDI like less than a week ago :)
Updated MDI again to latest 2.4.85. Will be available with Quasar CLI v0.16.2 or through quasar-extras 2.0.2 (if using vue-cli-plugin-quasar).

Thanks for reporting!
