### ISSUE TITLE
Upgrade dependency to font-awesome 5.2.0

### ISSUE THREAD

**Issue by jcperez-ch** [quasarframework/quasar-extras#19]
I just saw there are quite a bunch of useful new icons in 5.2.  I wish we can just upgrade the version to 5.2, Thanks

**Comment by jcperez-ch** [comment]
I just created the PR, let me know if all good
https://github.com/quasarframework/quasar-extras/pull/20

**Comment by rstoenescu** [comment]
PR merged. Thank you!
