### ISSUE TITLE
No PostCSS Config found

### ISSUE THREAD

**Issue by eaststrong** [quasarframework/quasar-extras#3]
ERROR  Failed to compile with 3 errors

 error  in ./node_modules/quasar-extras/material-icons/material-icons.css

Module build failed: Error: No PostCSS Config found in: C:\xxx\my-quasar-app\node_
modules\quasar-extras\material-icons
    at Error (native)
    at C:\xxx\my-quasar-app\node_modules\postcss-load-config\index.js:51:26

 @ ./node_modules/quasar-extras/material-icons/material-icons.css 4:14-127 13:3-
17:5 14:22-135
 @ ./node_modules/quasar-extras/material-icons.js
 @ ./src/main.js
 @ multi ./build/hot-reload.js ./src/main.js

 error  in ./node_modules/quasar-extras/roboto-font/roboto-font.css

Module build failed: Error: No PostCSS Config found in: C:\xxx\my-quasar-app\node_
modules\quasar-extras\roboto-font
    at Error (native)
    at C:\xxx\my-quasar-app\node_modules\postcss-load-config\index.js:51:26

 @ ./node_modules/quasar-extras/roboto-font/roboto-font.css 4:14-124 13:3-17:5 1
4:22-132
 @ ./node_modules/quasar-extras/roboto-font.js
 @ ./src/main.js
 @ multi ./build/hot-reload.js ./src/main.js

 error  in ./node_modules/quasar-framework/dist/quasar.mat.css

Module build failed: Error: No PostCSS Config found in: C:\xxx\my-quasar-app\node_
modules\quasar-framework\dist
    at Error (native)
    at C:\xxx\my-quasar-app\node_modules\postcss-load-config\index.js:51:26

 @ ./node_modules/quasar-framework/dist/quasar.mat.css 4:14-123 13:3-17:5 14:22-
131
 @ ./src/main.js
 @ multi ./build/hot-reload.js ./src/main.js

**Comment by rstoenescu** [comment]
I believe this is related to your project config. This does not happen with the default template. Any repo I can take a look?

**Comment by eaststrong** [comment]
Found the reason:

The version of postcss-loader should be below 1.3.3.
It doesn't work with 2.0.0 above.

**Comment by rstoenescu** [comment]
postcss-loader v2.0 vs v1.3 has breaking changes, yes. Will update template to postcss v2.0 soon.

**Comment by speyou** [comment]
If anyone is coming here from google, I had the same issue `No PostCSS Config found in: ...\my-quasar-app\node_modules\quasar-extras\material-icons`, it was due to my monorepo setup.
I fixed that by adding a `postcss.config.js` at the root of the monorepo.
My project is like this:
```
monorepo/
  /node_modules
  /packages
    |  /myProject1
    |    |  package.json <-- I execute my build command here
    |    |  postcss.config.js <-- I was thinking this one was enough but no
  postcss.config.js <-- I had to add this one here
```

**Comment by corepay** [comment]
@speyou speyou  can you tell us what you added in postcss.config.js?  A blank file...a file with a an empty object?  Does this even apply now as the latest quasar builds have a .postcssrc.js file (no knowledge of pre 1.0 builds...)

**Comment by speyou** [comment]
It's the same file as everywhere, I import a base file and I apply it.
Quasar 0.17 btw.

```
const postCssConfig = require("./packages/@configs/postcss.config.base.js");

module.exports = {
  ...postCssConfig
};
```

And the file is this. I don't have a strong knowledge about this so I just added something that worked and never touched it again.

_./packages/@configs/postcss.config.base.js_
```
module.exports = {
  plugins: {
    autoprefixer: {}
  }
};
```
