### ISSUE TITLE
update ionicons to v3

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar-extras#9]
- css files are available at https://unpkg.com/ionicons@3.0.0/dist/css/
- woff etc. files are available at https://unpkg.com/ionicons@3.0.0/dist/fonts/

(ionicon v4 is different as it is more for PWAs, with a custom `ion-icon` component to load only used icons)

**Comment by rstoenescu** [comment]
Ionicons v4 will be available in CLI v0.16.x in a few days.
